# Generated by Django 5.2.15 on 2026-06-29 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sleep', 'Sleep Detected'), ('awake', 'Awake Detected'), ('motion', 'Motion Detected'), ('cry', 'Cry Detected'), ('no_cry', 'No Cry')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('audio_level', models.FloatField(blank=True, null=True)),
                ('motion_level', models.FloatField(blank=True, null=True)),
                ('frame_data', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_events', to='core.babyprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
